---

- name: Install additional packages
  apt: name={{item}} state=present
  with_items:
   - git
   - wget
   
- name: Pull down and install Docker packages
  shell: chdir=/opt wget -qO- https://get.docker.com/ | sh
  
- name: Verify the Docker install
  command: docker run hello-world

- name: Add Nova user to Docker group
  command: usermod -aG docker nova